# Generated by Django 4.0 on 2021-12-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DONE', 'Task has been completed'), ('IN-PROGRESS', 'Task still needs to be completed'), ('NOT STARTED', 'Task has not been started')], default='NOT STARTED', max_length=20),
        ),
    ]
